---
driver:
    name: dokken
    chef_version: latest
    privileged: true
    forward:
      - 80
      - 443

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  # https://github.com/CentOS/sig-cloud-instance-images/issues/30
  # Unfortunately with a privileged container (required) the hostname doesn't
  # correctly set on CentOS 6.x. Commenting out until resolved
  # - name: centos-6
  #   driver:
  #     image: centos:6
  #     platform: rhel
  #     pid_one_command: /sbin/init
  #     intermediate_instructions:
  #       - RUN yum -y install which lsof initscripts yum-plugin-ovl

  # Only works with chef client 12.x - and still warns of error regarding chef_backend resource
  - name: centos-7
    driver:
      image: centos:7
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install which lsof net-utils

  - name: ubuntu-trusty
    driver:
      image: dokken/ubuntu-14.04
      platform: ubuntu
      pid_one_command: /sbin/init
      provision_command:
        - RUN /usr/bin/apt-get update

  - name: ubuntu-xenial
    driver:
      image: dokken/ubuntu-16.04
      platform: ubuntu
      pid_one_command: /bin/systemd
      provision_command:
        - RUN /usr/bin/apt update

suites:
  - name: default
    driver:
      hostname: compliance.localdomain.local
    run_list:
      - recipe[chef-compliance]
    attributes:
      chef-compliance:
        accept_license: true
        fqdn: 'compliance.localdomain.local'
