---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 4

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.7

suites:
  - name: default
    driver:
      vm_hostname: compliance.localdomain.local
    run_list:
      - recipe[chef-compliance]
    attributes:
      chef-compliance:
        fqdn: 'compliance.localdomain.local'
        accept_license: true
